name: demo
on:
  # Event/Action Types
  pull_request:
    types: 
      - opened
  # Manual execution
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Output event data
        run: |
            echo "date" > generated.txt
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "generated"
            git push